# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from client.api import api_pb2 as api__pb2


class DiceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RollDie = channel.unary_unary(
                '/api.DiceService/RollDie',
                request_serializer=api__pb2.RollDieRequest.SerializeToString,
                response_deserializer=api__pb2.RollDieResponse.FromString,
                )


class DiceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RollDie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RollDie': grpc.unary_unary_rpc_method_handler(
                    servicer.RollDie,
                    request_deserializer=api__pb2.RollDieRequest.FromString,
                    response_serializer=api__pb2.RollDieResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.DiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RollDie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.DiceService/RollDie',
            api__pb2.RollDieRequest.SerializeToString,
            api__pb2.RollDieResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
