# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='api',
  syntax='proto3',
  serialized_options=b'Z\nserver/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapi.proto\x12\x03\x61pi\"\x10\n\x0eRollDieRequest\" \n\x0fRollDieResponse\x12\r\n\x05value\x18\x01 \x01(\x05\x32\x45\n\x0b\x44iceService\x12\x36\n\x07RollDie\x12\x13.api.RollDieRequest\x1a\x14.api.RollDieResponse\"\x00\x42\x0cZ\nserver/apib\x06proto3'
)




_ROLLDIEREQUEST = _descriptor.Descriptor(
  name='RollDieRequest',
  full_name='api.RollDieRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=34,
)


_ROLLDIERESPONSE = _descriptor.Descriptor(
  name='RollDieResponse',
  full_name='api.RollDieResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.RollDieResponse.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['RollDieRequest'] = _ROLLDIEREQUEST
DESCRIPTOR.message_types_by_name['RollDieResponse'] = _ROLLDIERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RollDieRequest = _reflection.GeneratedProtocolMessageType('RollDieRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROLLDIEREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.RollDieRequest)
  })
_sym_db.RegisterMessage(RollDieRequest)

RollDieResponse = _reflection.GeneratedProtocolMessageType('RollDieResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROLLDIERESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.RollDieResponse)
  })
_sym_db.RegisterMessage(RollDieResponse)


DESCRIPTOR._options = None

_DICESERVICE = _descriptor.ServiceDescriptor(
  name='DiceService',
  full_name='api.DiceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=70,
  serialized_end=139,
  methods=[
  _descriptor.MethodDescriptor(
    name='RollDie',
    full_name='api.DiceService.RollDie',
    index=0,
    containing_service=None,
    input_type=_ROLLDIEREQUEST,
    output_type=_ROLLDIERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DICESERVICE)

DESCRIPTOR.services_by_name['DiceService'] = _DICESERVICE

# @@protoc_insertion_point(module_scope)
